"""initial

Revision ID: 47bd16d120cf
Revises: 
Create Date: 2026-01-31 12:09:28.842366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47bd16d120cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_doctor_start'), table_name='Shanmukh_appointments')
    op.drop_index(op.f('ix_Shanmukh_appointments_start_time'), table_name='Shanmukh_appointments')
    op.drop_table('Shanmukh_appointments')
    op.drop_index(op.f('email'), table_name='sowmya_patients')
    op.drop_table('sowmya_patients')
    op.drop_index(op.f('ix_harshitha_appointments_start_time'), table_name='harshitha_appointments')
    op.drop_table('harshitha_appointments')
    op.drop_index(op.f('ix_diksha-patients1_email'), table_name='diksha-patients1')
    op.drop_table('diksha-patients1')
    op.drop_table('ganesh_patients')
    op.drop_index(op.f('ix_sivapriya_appointments_start_time'), table_name='sivapriya_appointments')
    op.drop_table('sivapriya_appointments')
    op.drop_table('althamash_appointments')
    op.drop_table('vamsi_doctors')
    op.drop_table('vaishnaviCH_appointments')
    op.drop_index(op.f('ix_appointments_doctor_start'), table_name='parthGeraAppointments')
    op.drop_index(op.f('ix_parthGeraAppointments_start_time'), table_name='parthGeraAppointments')
    op.drop_table('parthGeraAppointments')
    op.drop_table('akshara_appointments')
    op.drop_table('diksha_test_table')
    op.drop_table('KoushikDoctors')
    op.drop_index(op.f('ix_vignesh_doctors_id'), table_name='vignesh_doctors')
    op.drop_table('vignesh_doctors')
    op.drop_index(op.f('idx_doctor_start'), table_name='sowmya_appointments')
    op.drop_table('sowmya_appointments')
    op.drop_table('diksha_books')
    op.drop_table('sivapriya_books')
    op.drop_table('vaishnavik_doctors')
    op.drop_table('diksha_patients')
    op.drop_table('sowmya_doctors')
    op.drop_table('spoorthi_patients')
    op.drop_table('umar_test_table')
    op.drop_table('avi_appointments')
    op.drop_table('Vaishnavik_doctors')
    op.drop_table('diksha_doctors')
    op.drop_table('althamash_doctors')
    op.drop_table('appointments')
    op.drop_table('test_table')
    op.drop_table('parthGeraDoctors')
    op.drop_table('ALEKHYA_BOOKS')
    op.drop_table('nagaraj_appointments')
    op.drop_table('Shanmukh_doctors')
    op.drop_table('akshara_doctors')
    op.drop_index(op.f('email'), table_name='Shanmukh_patients')
    op.drop_table('Shanmukh_patients')
    op.drop_index(op.f('title'), table_name='ganesh_books')
    op.drop_table('ganesh_books')
    op.drop_index(op.f('ix_vaishnavik_patients_email'), table_name='vaishnavik_patients')
    op.drop_table('vaishnavik_patients')
    op.drop_table('varun_doctors')
    op.drop_index(op.f('ix_gurman_Patients_email'), table_name='gurman_Patients')
    op.drop_table('gurman_Patients')
    op.drop_table('doctors')
    op.drop_table('spoorthi_books')
    op.drop_index(op.f('idx_doctor_start_time'), table_name='aaryan_singh_appointments')
    op.drop_table('aaryan_singh_appointments')
    op.drop_table('Omkaar_appointments')
    op.drop_table('Poojitha_books')
    op.drop_table('vaishnaviCH_doctors')
    op.drop_table('ganesh_doctors')
    op.drop_table('prashanthi_books')
    op.drop_table('parthAppointments')
    op.drop_table('avibooks')
    op.drop_table('sruthi_appointments')
    op.drop_table('gurman_Doctors')
    op.drop_table('Alekhya_appointments')
    op.drop_index(op.f('ix_appointments_doctor_start'), table_name='gurman_Appointments')
    op.drop_index(op.f('ix_gurman_Appointments_start_time'), table_name='gurman_Appointments')
    op.drop_table('gurman_Appointments')
    op.drop_index(op.f('ix_ganesh_b_doctors_is_active'), table_name='ganesh_b_doctors')
    op.drop_table('ganesh_b_doctors')
    op.drop_table('umar_appointments')
    op.drop_index(op.f('uq_althamash_patients_email'), table_name='althamash_patients')
    op.drop_table('althamash_patients')
    op.drop_table('vignesh_books')
    op.drop_table('parthDoctors')
    op.drop_index(op.f('ix_saniya_appointments_start_time'), table_name='saniya_appointments')
    op.drop_table('saniya_appointments')
    op.drop_table('varun_books')
    op.drop_index(op.f('email'), table_name='saniya_patients')
    op.drop_table('saniya_patients')
    op.drop_table('umar_books')
    op.drop_table('prashanthi_appointments')
    op.drop_table('akshara_patients')
    op.drop_table('KoushikAppointments')
    op.drop_table('sivapriya_doctors')
    op.drop_table('aaryan_singh_alembic_version')
    op.drop_index(op.f('ix_vamsi_appointments_appointment_start_datetime'), table_name='vamsi_appointments')
    op.drop_table('vamsi_appointments')
    op.drop_index(op.f('ix_vignesh_patients_email'), table_name='vignesh_patients')
    op.drop_index(op.f('ix_vignesh_patients_id'), table_name='vignesh_patients')
    op.drop_table('vignesh_patients')
    op.drop_table('Aaryan_appointments')
    op.drop_table('sruthi_doctors')
    op.drop_index(op.f('ix_diksha-doctors1_id'), table_name='diksha-doctors1')
    op.drop_table('diksha-doctors1')
    op.drop_table('parthPatients')
    op.drop_index(op.f('ix_diksha-appointments1_start_datetime'), table_name='diksha-appointments1')
    op.drop_table('diksha-appointments1')
    op.drop_table('Shanmukh_books')
    op.drop_index(op.f('email'), table_name='harshitha_patients')
    op.drop_table('harshitha_patients')
    op.drop_index(op.f('ix_ganesh_b_patients_email'), table_name='ganesh_b_patients')
    op.drop_table('ganesh_b_patients')
    op.drop_table('vaishnaviCH_books')
    op.drop_table('likhitha_appointments')
    op.drop_table('test_table1')
    op.drop_table('avi_doctors')
    op.drop_table('Omkaar_patients')
    op.drop_table('koushik_books')
    op.drop_index(op.f('ix_vignesh_appointments_id'), table_name='vignesh_appointments')
    op.drop_index(op.f('ix_vignesh_appointments_start_time'), table_name='vignesh_appointments')
    op.drop_table('vignesh_appointments')
    op.drop_table('likhitha_patients')
    op.drop_table('prashanthi_doctors')
    op.drop_table('sowmya_books')
    op.drop_table('gurman_books')
    op.drop_table('nagaraj_books')
    op.drop_table('aaryan_singh_doctors')
    op.drop_table('spoorthi_appointments')
    op.drop_index(op.f('email'), table_name='vamsi_patients')
    op.drop_table('vamsi_patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_parthGeraPatients_email'), table_name='parthGeraPatients')
    op.drop_table('parthGeraPatients')
    op.drop_index(op.f('ix_aaryan_singh_patients_email'), table_name='aaryan_singh_patients')
    op.drop_table('aaryan_singh_patients')
    op.drop_table('umar_doctors')
    op.drop_index(op.f('ix_koushik_patients_email'), table_name='koushik_patients')
    op.drop_table('koushik_patients')
    op.drop_table('books')
    op.drop_table('prashanthi_patients')
    op.drop_table('avi_patients')
    op.drop_table('varun_appointments')
    op.drop_table('spoorthi_doctors')
    op.drop_index(op.f('ix_ganesh_b_appointments_doctor_id'), table_name='ganesh_b_appointments')
    op.drop_index(op.f('ix_ganesh_b_appointments_patient_id'), table_name='ganesh_b_appointments')
    op.drop_index(op.f('ix_ganesh_b_appointments_start_datetime'), table_name='ganesh_b_appointments')
    op.drop_table('ganesh_b_appointments')
    op.drop_table('saniya_doctors')
    op.drop_table('Aaryan_patients')
    op.drop_table('Vaishnavik_patients')
    op.drop_table('sruthi_patients')
    op.drop_table('likhitha_doctors')
    op.drop_table('Vaishnavik_appointments')
    op.drop_index(op.f('ix_koushik_appointments_start_time'), table_name='koushik_appointments')
    op.drop_index(op.f('koushik_idx_doctor_start'), table_name='koushik_appointments')
    op.drop_table('koushik_appointments')
    op.drop_table('varshini_books')
    op.drop_table('avi_testtable')
    op.drop_table('akshara_books')
    op.drop_table('poojitha_doctors')
    op.drop_table('Alekhya_patients')
    op.drop_table('sruthi_books')
    op.drop_table('Alekhya_doctors')
    op.drop_table('diksha_appointments')
    op.drop_table('Aaryan_doctors')
    op.drop_table('koushikPatients')
    op.drop_table('althamash_books')
    op.drop_table('ganesh_appointments')
    op.drop_table('poojitha_appointments')
    op.drop_table('vaishnaviCH_patients')
    op.drop_table('likhitha_books')
    op.drop_table('umar_patients')
    op.drop_table('saniya_books')
    op.drop_index(op.f('ix_sivapriya_patients_email'), table_name='sivapriya_patients')
    op.drop_table('sivapriya_patients')
    op.drop_table('Omkaar_books')
    op.drop_table('varun_patients')
    op.drop_table('Omkaar_doctors')
    op.drop_table('poojitha_patients')
    op.drop_table('harshitha_doctors')
    op.drop_table('koushik_doctors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('koushik_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('harshitha_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('poojitha_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Omkaar_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('varun_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Omkaar_books',
    sa.Column('Title', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('Author', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sivapriya_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sivapriya_patients_email'), 'sivapriya_patients', ['email'], unique=True)
    op.create_table('saniya_books',
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('umar_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('likhitha_books',
    sa.Column('title', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vaishnaviCH_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('poojitha_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['poojitha_doctors.id'], name=op.f('poojitha_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['poojitha_patients.id'], name=op.f('poojitha_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ganesh_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['ganesh_doctors.id'], name=op.f('ganesh_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['ganesh_patients.id'], name=op.f('ganesh_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('althamash_books',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('koushikPatients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Aaryan_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('diksha_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['diksha_doctors.id'], name=op.f('diksha_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['diksha_patients.id'], name=op.f('diksha_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Alekhya_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sruthi_books',
    sa.Column('title', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Alekhya_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('poojitha_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('akshara_books',
    sa.Column('title', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('published_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('avi_testtable',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('varshini_books',
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('koushik_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['koushik_doctors.id'], name=op.f('koushik_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['koushik_patients.id'], name=op.f('koushik_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('koushik_idx_doctor_start'), 'koushik_appointments', ['doctor_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_koushik_appointments_start_time'), 'koushik_appointments', ['start_time'], unique=False)
    op.create_table('Vaishnavik_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Vaishnavik_doctors.id'], name=op.f('Vaishnavik_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['Vaishnavik_patients.id'], name=op.f('Vaishnavik_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('likhitha_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sruthi_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Vaishnavik_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Aaryan_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('saniya_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ganesh_b_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_datetime', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['ganesh_b_doctors.id'], name=op.f('ganesh_b_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['ganesh_b_patients.id'], name=op.f('ganesh_b_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ganesh_b_appointments_start_datetime'), 'ganesh_b_appointments', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_ganesh_b_appointments_patient_id'), 'ganesh_b_appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ganesh_b_appointments_doctor_id'), 'ganesh_b_appointments', ['doctor_id'], unique=False)
    op.create_table('spoorthi_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('varun_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['varun_doctors.id'], name=op.f('varun_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['varun_patients.id'], name=op.f('varun_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('avi_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('prashanthi_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('books',
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('koushik_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_koushik_patients_email'), 'koushik_patients', ['email'], unique=True)
    op.create_table('umar_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('aaryan_singh_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_aaryan_singh_patients_email'), 'aaryan_singh_patients', ['email'], unique=True)
    op.create_table('parthGeraPatients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_parthGeraPatients_email'), 'parthGeraPatients', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vamsi_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8_unicode_ci', length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'vamsi_patients', ['email'], unique=True)
    op.create_table('spoorthi_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['spoorthi_doctors.id'], name=op.f('spoorthi_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['spoorthi_patients.id'], name=op.f('spoorthi_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('aaryan_singh_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('nagaraj_books',
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('gurman_books',
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sowmya_books',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('book_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('prashanthi_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('likhitha_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vignesh_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['vignesh_doctors.id'], name=op.f('vignesh_appointments_ibfk_1')),
    sa.ForeignKeyConstraint(['patient_id'], ['vignesh_patients.id'], name=op.f('vignesh_appointments_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_vignesh_appointments_start_time'), 'vignesh_appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_vignesh_appointments_id'), 'vignesh_appointments', ['id'], unique=False)
    op.create_table('koushik_books',
    sa.Column('title', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Omkaar_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('avi_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('test_table1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('likhitha_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['likhitha_doctors.id'], name=op.f('likhitha_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['likhitha_patients.id'], name=op.f('likhitha_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vaishnaviCH_books',
    sa.Column('title', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ganesh_b_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ganesh_b_patients_email'), 'ganesh_b_patients', ['email'], unique=True)
    op.create_table('harshitha_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'harshitha_patients', ['email'], unique=True)
    op.create_table('Shanmukh_books',
    sa.Column('Title', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('Author', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('diksha-appointments1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_datetime', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['diksha-doctors1.id'], name=op.f('diksha-appointments1_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['diksha-patients1.id'], name=op.f('diksha-appointments1_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_diksha-appointments1_start_datetime'), 'diksha-appointments1', ['start_datetime'], unique=False)
    op.create_table('parthPatients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('diksha-doctors1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_diksha-doctors1_id'), 'diksha-doctors1', ['id'], unique=False)
    op.create_table('sruthi_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Aaryan_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Aaryan_doctors.id'], name=op.f('Aaryan_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['Aaryan_patients.id'], name=op.f('Aaryan_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vignesh_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_vignesh_patients_id'), 'vignesh_patients', ['id'], unique=False)
    op.create_index(op.f('ix_vignesh_patients_email'), 'vignesh_patients', ['email'], unique=True)
    op.create_table('vamsi_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('appointment_start_datetime', mysql.DATETIME(), nullable=False),
    sa.Column('appointment_duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['vamsi_doctors.id'], name=op.f('vamsi_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['vamsi_patients.id'], name=op.f('vamsi_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_vamsi_appointments_appointment_start_datetime'), 'vamsi_appointments', ['appointment_start_datetime'], unique=False)
    op.create_table('aaryan_singh_alembic_version',
    sa.Column('version_num', mysql.VARCHAR(collation='utf8_unicode_ci', length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sivapriya_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('KoushikAppointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['KoushikDoctors.id'], name=op.f('KoushikAppointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['koushikPatients.id'], name=op.f('KoushikAppointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('akshara_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('prashanthi_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['prashanthi_doctors.id'], name=op.f('prashanthi_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['prashanthi_patients.id'], name=op.f('prashanthi_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('umar_books',
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('saniya_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'saniya_patients', ['email'], unique=True)
    op.create_table('varun_books',
    sa.Column('book_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('saniya_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['saniya_doctors.id'], name=op.f('saniya_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['saniya_patients.id'], name=op.f('saniya_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_saniya_appointments_start_time'), 'saniya_appointments', ['start_time'], unique=False)
    op.create_table('parthDoctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vignesh_books',
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('book_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('althamash_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_althamash_patients_email'), 'althamash_patients', ['email'], unique=True)
    op.create_table('umar_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['umar_doctors.id'], name=op.f('umar_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['umar_patients.id'], name=op.f('umar_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ganesh_b_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ganesh_b_doctors_is_active'), 'ganesh_b_doctors', ['is_active'], unique=False)
    op.create_table('gurman_Appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['gurman_Doctors.id'], name=op.f('gurman_Appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['gurman_Patients.id'], name=op.f('gurman_Appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gurman_Appointments_start_time'), 'gurman_Appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_start'), 'gurman_Appointments', ['doctor_id', 'start_time'], unique=False)
    op.create_table('Alekhya_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Alekhya_doctors.id'], name=op.f('Alekhya_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['Alekhya_patients.id'], name=op.f('Alekhya_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('gurman_Doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sruthi_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['sruthi_doctors.id'], name=op.f('sruthi_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['sruthi_patients.id'], name=op.f('sruthi_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('avibooks',
    sa.Column('title', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('parthAppointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['parthDoctors.id'], name=op.f('parthAppointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['parthPatients.id'], name=op.f('parthAppointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('prashanthi_books',
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ganesh_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vaishnaviCH_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Poojitha_books',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Omkaar_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Omkaar_doctors.id'], name=op.f('Omkaar_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['Omkaar_patients.id'], name=op.f('Omkaar_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('aaryan_singh_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['aaryan_singh_doctors.id'], name=op.f('aaryan_singh_appointments_ibfk_1')),
    sa.ForeignKeyConstraint(['patient_id'], ['aaryan_singh_patients.id'], name=op.f('aaryan_singh_appointments_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_doctor_start_time'), 'aaryan_singh_appointments', ['doctor_id', 'start_time'], unique=False)
    op.create_table('spoorthi_books',
    sa.Column('title', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('gurman_Patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gurman_Patients_email'), 'gurman_Patients', ['email'], unique=True)
    op.create_table('varun_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vaishnavik_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_vaishnavik_patients_email'), 'vaishnavik_patients', ['email'], unique=True)
    op.create_table('ganesh_books',
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=30), nullable=False),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('title'), 'ganesh_books', ['title'], unique=True)
    op.create_table('Shanmukh_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=False),
    sa.Column('created_timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('updated_timestamp', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'Shanmukh_patients', ['email'], unique=True)
    op.create_table('akshara_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Shanmukh_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_timestamp', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('nagaraj_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('nagaraj_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('nagaraj_appointments_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ALEKHYA_BOOKS',
    sa.Column('name', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('parthGeraDoctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('test_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('appointments_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('althamash_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('diksha_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Vaishnavik_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('avi_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['avi_doctors.id'], name=op.f('avi_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['avi_patients.id'], name=op.f('avi_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('umar_test_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('spoorthi_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sowmya_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('diksha_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vaishnavik_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sivapriya_books',
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('diksha_books',
    sa.Column('title', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('author', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sowmya_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['sowmya_doctors.id'], name=op.f('sowmya_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['sowmya_patients.id'], name=op.f('sowmya_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_doctor_start'), 'sowmya_appointments', ['doctor_id', 'start_time'], unique=False)
    op.create_table('vignesh_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_vignesh_doctors_id'), 'vignesh_doctors', ['id'], unique=False)
    op.create_table('KoushikDoctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('diksha_test_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('akshara_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['akshara_doctors.id'], name=op.f('akshara_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['akshara_patients.id'], name=op.f('akshara_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('parthGeraAppointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['parthGeraDoctors.id'], name=op.f('parthGeraAppointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['parthGeraPatients.id'], name=op.f('parthGeraAppointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_parthGeraAppointments_start_time'), 'parthGeraAppointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_start'), 'parthGeraAppointments', ['doctor_id', 'start_time'], unique=False)
    op.create_table('vaishnaviCH_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['vaishnaviCH_doctors.id'], name=op.f('vaishnaviCH_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['vaishnaviCH_patients.id'], name=op.f('vaishnaviCH_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vamsi_doctors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('active_status', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('althamash_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sivapriya_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['sivapriya_doctors.id'], name=op.f('sivapriya_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['sivapriya_patients.id'], name=op.f('sivapriya_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sivapriya_appointments_start_time'), 'sivapriya_appointments', ['start_time'], unique=False)
    op.create_table('ganesh_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('diksha-patients1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=15), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_diksha-patients1_email'), 'diksha-patients1', ['email'], unique=True)
    op.create_table('harshitha_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['harshitha_doctors.id'], name=op.f('harshitha_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['harshitha_patients.id'], name=op.f('harshitha_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_harshitha_appointments_start_time'), 'harshitha_appointments', ['start_time'], unique=False)
    op.create_table('sowmya_patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'sowmya_patients', ['email'], unique=True)
    op.create_table('Shanmukh_appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Shanmukh_doctors.id'], name=op.f('Shanmukh_appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['Shanmukh_patients.id'], name=op.f('Shanmukh_appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Shanmukh_appointments_start_time'), 'Shanmukh_appointments', ['start_time'], unique=False)
    op.create_index(op.f('idx_doctor_start'), 'Shanmukh_appointments', ['doctor_id', 'start_time'], unique=False)
    # ### end Alembic commands ###
